Repository osbuild/images, pull requests merged in 2025-01, with the labels that each got.

#1123 Test/scripts: move shared code to `imgtestlib` (HMS-5242)
  test/scripts/boot-image
  test/scripts/build-image
  test/scripts/imgtestlib.py
  test/scripts/upload-results
Labels: 🌟 best practice

#1152 Test/scripts/build-info: include runner-distro in `info.json` (HMS-5350)
  test/scripts/build-image
Labels: :baby_bottle: Simple, 🌟 best practice

#1164 osbuild: add consts for more "sources" in sources.go
  pkg/osbuild/containers_input.go
  pkg/osbuild/containers_storage_source.go
  pkg/osbuild/skopeo_index_source.go
  pkg/osbuild/skopeo_source.go
  pkg/osbuild/skopeo_stage.go
  pkg/osbuild/source.go
Labels: :baby_bottle: Simple

#1170 distro: use `rand.Int63` intead of `time.UnixNano()`
  pkg/distro/distro.go
Labels: :baby_bottle: Simple
